export const ActionTypes = {
    SET_PEOPLE: "SET_PEOPLE",
    SELECTED_PEOPLE: "SELECTED_PEOPLE",
    REMOVE_SELECTED_PEOPLE: "REMOVE_SELECTED_PEOPLE",
    SELECTED_CHAT: "SELECTED_CHAT",
    REMOVE_CHAT: "REMOVE_CHAT"
}